name: Compilar APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar herramientas del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y libtool autoconf unzip pkg-config build-essential libffi-dev python3-dev

      - name: Instalar Buildozer y librerias
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.37 fpdf2

      - name: Crear configuracion de Buildozer limpia
        run: |
          buildozer init
          # Reemplazamos la linea de requisitos de forma directa y garantizada
          sed -i 's/^requirements = .*/requirements = python3,kivy,sqlite3,fpdf2/g' buildozer.spec
          # Forzamos el log detallado por si las moscas
          sed -i 's/^log_level = .*/log_level = 2/g' buildozer.spec

      - name: Compilar APK
        run: |
          yes y | buildozer -v android debug

      - name: Guardar el APK terminado
        uses: actions/upload-artifact@v4
        with:
          name: Mi-APK-Listo
          path: bin/*.apk
